-- Create tables for Bangkok districts and provinces
CREATE TABLE IF NOT EXISTS CCI_bangkok_districts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name_th VARCHAR(255) NOT NULL,
  name_en VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS CCI_provinces (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name_th VARCHAR(255) NOT NULL,
  name_en VARCHAR(255) NOT NULL
);

-- Insert Bangkok districts
INSERT INTO CCI_bangkok_districts (name_th, name_en) VALUES
('เขตพระนคร', 'Phra Nakhon'),
('เขตดุสิต', 'Dusit'),
('เขตหนองจอก', 'Nong Chok'),
('เขตบางรัก', 'Bang Rak'),
('เขตบางเขน', 'Bang Khen'),
('เขตบางกะปิ', 'Bang Kapi'),
('เขตปทุมวัน', 'Pathum Wan'),
('เขตป้อมปราบศัตรูพ่าย', 'Pom Prap Sattru Phai'),
('เขตพระโขนง', 'Phra Khanong'),
('เขตมีนบุรี', 'Min Buri'),
('เขตลาดกระบัง', 'Lat Krabang'),
('เขตยานนาวา', 'Yan Nawa'),
('เขตสัมพันธวงศ์', 'Samphanthawong'),
('เขตพญาไท', 'Phaya Thai'),
('เขตธนบุรี', 'Thon Buri'),
('เขตบางกอกใหญ่', 'Bangkok Yai'),
('เขตห้วยขวาง', 'Huai Khwang'),
('เขตคลองสาน', 'Khlong San'),
('เขตตลิ่งชัน', 'Taling Chan'),
('เขตบางกอกน้อย', 'Bangkok Noi'),
('เขตบางขุนเทียน', 'Bang Khun Thian'),
('เขตภาษีเจริญ', 'Phasi Charoen'),
('เขตหนองแขม', 'Nong Khaem'),
('เขตราษฎร์บูรณะ', 'Rat Burana'),
('เขตบางพลัด', 'Bang Phlat'),
('เขตดินแดง', 'Din Daeng'),
('เขตบึงกุ่ม', 'Bueng Kum'),
('เขตสาทร', 'Sathon'),
('เขตบางซื่อ', 'Bang Sue'),
('เขตจตุจักร', 'Chatuchak'),
('เขตบางคอแหลม', 'Bang Kho Laem'),
('เขตประเวศ', 'Prawet'),
('เขตคลองเตย', 'Khlong Toei'),
('เขตสวนหลวง', 'Suan Luang'),
('เขตจอมทอง', 'Chom Thong'),
('เขตดอนเมือง', 'Don Mueang'),
('เขตราชเทวี', 'Ratchathewi'),
('เขตลาดพร้าว', 'Lat Phrao'),
('เขตวัฒนา', 'Watthana'),
('เขตบางแค', 'Bang Khae'),
('เขตหลักสี่', 'Lak Si'),
('เขตสายไหม', 'Sai Mai'),
('เขตคันนายาว', 'Khan Na Yao'),
('เขตสะพานสูง', 'Saphan Sung'),
('เขตวังทองหลาง', 'Wang Thonglang'),
('เขตคลองสามวา', 'Khlong Sam Wa'),
('เขตบางนา', 'Bang Na'),
('เขตทวีวัฒนา', 'Thawi Watthana'),
('เขตทุ่งครุ', 'Thung Khru'),
('เขตบางบอน', 'Bang Bon');

-- Insert provinces
INSERT INTO CCI_provinces (name_th, name_en) VALUES
('กระบี่', 'Krabi'),
('กาญจนบุรี', 'Kanchanaburi'),
('กาฬสินธุ์', 'Kalasin'),
('กำแพงเพชร', 'Kamphaeng Phet'),
('ขอนแก่น', 'Khon Kaen'),
('จันทบุรี', 'Chanthaburi'),
('ฉะเชิงเทรา', 'Chachoengsao'),
('ชลบุรี', 'Chonburi'),
('ชัยนาท', 'Chai Nat'),
('ชัยภูมิ', 'Chaiyaphum'),
('ชุมพร', 'Chumphon'),
('เชียงราย', 'Chiang Rai'),
('เชียงใหม่', 'Chiang Mai'),
('ตรัง', 'Trang'),
('ตราด', 'Trat'),
('ตาก', 'Tak'),
('นครนายก', 'Nakhon Nayok'),
('นครปฐม', 'Nakhon Pathom'),
('นครพนม', 'Nakhon Phanom'),
('นครราชสีมา', 'Nakhon Ratchasima'),
('นครศรีธรรมราช', 'Nakhon Si Thammarat'),
('นครสวรรค์', 'Nakhon Sawan'),
('นนทบุรี', 'Nonthaburi'),
('นราธิวาส', 'Narathiwat'),
('น่าน', 'Nan'),
('บึงกาฬ', 'Bueng Kan'),
('บุรีรัมย์', 'Buriram'),
('ปทุมธานี', 'Pathum Thani'),
('ประจวบคีรีขันธ์', 'Prachuap Khiri Khan'),
('ปราจีนบุรี', 'Prachinburi'),
('ปัตตานี', 'Pattani'),
('พะเยา', 'Phayao'),
('พระนครศรีอยุธยา', 'Phra Nakhon Si Ayutthaya'),
('พังงา', 'Phang Nga'),
('พัทลุง', 'Phatthalung'),
('พิจิตร', 'Phichit'),
('พิษณุโลก', 'Phitsanulok'),
('เพชรบุรี', 'Phetchaburi'),
('เพชรบูรณ์', 'Phetchabun'),
('แพร่', 'Phrae'),
('ภูเก็ต', 'Phuket'),
('มหาสารคาม', 'Maha Sarakham'),
('มุกดาหาร', 'Mukdahan'),
('แม่ฮ่องสอน', 'Mae Hong Son'),
('ยโสธร', 'Yasothon'),
('ยะลา', 'Yala'),
('ร้อยเอ็ด', 'Roi Et'),
('ระนอง', 'Ranong'),
('ระยอง', 'Rayong'),
('ราชบุรี', 'Ratchaburi'),
('ลพบุรี', 'Lopburi'),
('ลำปาง', 'Lampang'),
('ลำพูน', 'Lamphun'),
('เลย', 'Loei'),
('ศรีสะเกษ', 'Si Sa Ket'),
('สกลนคร', 'Sakon Nakhon'),
('สงขลา', 'Songkhla'),
('สตูล', 'Satun'),
('สมุทรปราการ', 'Samut Prakan'),
('สมุทรสงคราม', 'Samut Songkhram'),
('สมุทรสาคร', 'Samut Sakhon'),
('สระแก้ว', 'Sa Kaeo'),
('สระบุรี', 'Saraburi'),
('สิงห์บุรี', 'Sing Buri'),
('สุโขทัย', 'Sukhothai'),
('สุพรรณบุรี', 'Suphan Buri'),
('สุราษฎร์ธานี', 'Surat Thani'),
('สุรินทร์', 'Surin'),
('หนองคาย', 'Nong Khai'),
('หนองบัวลำภู', 'Nong Bua Lamphu'),
('อ่างทอง', 'Ang Thong'),
('อำนาจเจริญ', 'Amnat Charoen'),
('อุดรธานี', 'Udon Thani'),
('อุตรดิตถ์', 'Uttaradit'),
('อุทัยธานี', 'Uthai Thani'),
('อุบลราชธานี', 'Ubon Ratchathani');

-- Add location fields to registrants table
ALTER TABLE CCI_registrants ADD COLUMN location_type ENUM('bangkok', 'province') NULL AFTER car_passenger_type;
ALTER TABLE CCI_registrants ADD COLUMN bangkok_district_id INT NULL AFTER location_type;
ALTER TABLE CCI_registrants ADD COLUMN province_id INT NULL AFTER bangkok_district_id;
ALTER TABLE CCI_registrants ADD FOREIGN KEY (bangkok_district_id) REFERENCES CCI_bangkok_districts(id);
ALTER TABLE CCI_registrants ADD FOREIGN KEY (province_id) REFERENCES CCI_provinces(id);
